// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfgjkoptrdokekikmrkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmZ2prb3B0cmRva2VraWttcmt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMjA2NjksImV4cCI6MjA2MDY5NjY2OX0.pVsuY4zjbyegQdag1rabK9p5ateFkC_hISciXaP0Ptk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);